# -*- coding: utf-8 -*-
"""Task-1(CB)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1vi0e4VObD0YOii5Uik4YwiKqYTuGfx
"""

#1 Write a program to return highest number of times a character has occurred in a string.
s=input("Enter The String ")
max_count = 0
most_freq_cha=''
checked_cha=''

for i in s:
    if i not in checked_cha and  i!='':
      count=s.count(i)
      if count>max_count:
           max_count = count
           most_freq_cha = i
      checked_cha +=i

print("The character with Highest Frequency " , most_freq_cha)
print("Number of times ",max_count)

#2 Write a program to count number of Vowels & Consonants in a sentence.
sentence=input("Enter The Sentence : ")
vowels=['a','e','i','o','u']
vowel_count=0
consonant_count=0
sentence=sentence.lower()

for i in sentence:
  if i.isalpha():
    if i in vowels:
      vowel_count+=1
    else :
      consonant_count+=1

print("Number of Vowels : ",vowel_count)
print("Number of consonant : ",consonant_count)

#3 Write a program find the Transpose of a given Matrix.
import numpy as np
m=np.matrix([[1,2],[3,4]])
n=m.transpose()
print(n)

#4 Write a program to find Union & Intersection of 2 lists.
s=list(map(int,input("Enter The List : ").split()))
l=list(map(int,input("Enter The List : ").split()))
union_of_list=list(set(s+l))
Intersection_of_List= list(set(s) & set(l))
print(union_of_list)
print(Intersection_of_List)

# # Write a program to find two Elements in an list such that their Sum is Closest to Zero.
# l=list(map(int,input("Enter The List : ").split()))
# a=sorted(l)
# print("The Two Element in the list having their sum Closet to zero are ", a[0], ':',a[1])

#this program work if all numbers +ve

#5 Write a program to find two Elements in an list such that their Sum is Closest to Zero.
l=list(map(int,input("Enter The List : ").split()))
num1,num2=0,0
min_sum=float('inf')

for i in range(len(l)):
  for j in range(i+1,len(l)):
    total=l[i]+l[j]
    if abs(total)<abs(min_sum):
        min_sum=total
        num1,num2=l[i],l[j]

print("Two Elements in an list such that their Sum is Closest to Zero are : ",num1 ,':',num2)
print("There Sum is :",min_sum)

#6 Write a program to find Largest & Smallest Word in a String.
s=input("Enter The String : ")
word=s.split()
smallest=largest=word[0]

for i in word :
  if len(i)<len(smallest):
    smallest=i
  if len(i)>len(smallest):
    largest=i

print("The smallest word in the String is : ",smallest)
print("The largest word in the String is : ",)

#7 Write a program to find Median of Elements after Merging 2 list.
l=list(map(int,input("Enter The List : ").split()))
x=list(map(int,input("Enter The List : ").split()))
a=l+x
a.sort()
print(a)
n=len(a)



if n%2 !=0 :
  median=(n)//2
  print("median is : ",a[median])
else :
  N=n//2
  median=(a[N]+a[N-1])/2

  print("median is : ",median)